### ISSUE TITLE
Lua Error when robbing

### ISSUE THREAD

**Issue by ghost** [n00bmobile/Bank-Robbery-System#3] opened 2015-04-19 16:44 UTC
When I press E to try and rob the bank I get this error in the server console;

[ERROR] addons/darkrp bank robbery system/lua/bank_server.lua:115: attempt to ca
ll method 'Notify' (a nil value)
1. BANK_BeginRobbery - addons/darkrp bank robbery system/lua/bank_server.lua:1
   15
   1. unknown - addons/darkrp bank robbery system/lua/entities/bank_vault/init.l
      ua:57

**Comment by n00bmobile** [comment] 2015-05-12 19:12
Hmmm... "Notify" is not in the code. Try redownload it or just replace "Notify" with "notify".

**Comment by n00bmobile** [comment] 2015-05-13 16:45
Download the newest version, this issue is caused by you. Contact me on Steam if you have setup questions. I'm closing this issue.

**Closed as completed** 2015-05-13 16:45 UTC
